# Generated by Django 5.1.2 on 2024-10-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_attributetype_remove_attribute_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='experience_points',
            new_name='experience_to_spend',
        ),
        migrations.AddField(
            model_name='character',
            name='experience_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
