# Generated by Django 5.1.2 on 2024-10-31 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_remove_character_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='level',
            new_name='default_level',
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='characters.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='characters.skill')),
            ],
        ),
    ]
