# Generated by Django 5.1.2 on 2024-11-01 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_rename_level_skill_default_level_characterskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastered_campaigns', to=settings.AUTH_USER_MODEL)),
                ('characters', models.ManyToManyField(blank=True, related_name='campaigns', to='characters.character')),
            ],
        ),
    ]
