# Generated by Django 5.1.2 on 2024-11-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_alter_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_campaign_requests', to='characters.character'),
        ),
    ]
