# Generated by Django 5.1.2 on 2024-11-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_character_request_campaign_character_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='request_campaign',
        ),
        migrations.RemoveField(
            model_name='character',
            name='request_status',
        ),
    ]
