# Generated by Django 5.1.2 on 2024-11-06 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_role_alter_character_character_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_value', models.IntegerField(default=25)),
                ('max_value', models.IntegerField(default=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='character',
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='characters.character')),
                ('characteristic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.characteristictype')),
            ],
        ),
        migrations.DeleteModel(
            name='AttributeType',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
