# Generated by Django 5.1.2 on 2024-11-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_characteristictype_remove_attribute_attribute_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristictype',
            name='primary_aptitude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_characteristics', to='characters.aptitude'),
        ),
        migrations.AddField(
            model_name='characteristictype',
            name='secondary_aptitude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_characteristics', to='characters.aptitude'),
        ),
    ]
