# Generated by Django 5.1.2 on 2024-11-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_characteristictype_primary_aptitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristictype',
            name='aptitudes',
            field=models.ManyToManyField(blank=True, related_name='characteristics', to='characters.aptitude'),
        ),
    ]
